# system configuration
system:
  use-multipoint: false
  env: 'public'
  addr: 5050
  db-type: 'mysql'
  need-init-data: false

# mysql configuration
mysql:
  username: root
#  password: 'kel317-+'
  password: '123456'
  path: '127.0.0.1:3306'
  db-name: 'apk_link_db'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  max-idle-conns: 50
  max-open-conns: 100
  log-mode: false

# redis configuration
redis:
  addr: '127.0.0.1:6379'
  password: ''
  db: 0

# aliyun-oss configuration
aliyun:
  access-key-id: 'LTAI4GLCwofVysdJqYgFF5sQ'
  access-key-secret: 'XP8nyjdTL55DIwMv7dB7IdMaY3I0Bo'
  bucket: 'sdkfile'
  region: 'oss-cn-beijing'
  endpoint: 'sdkfile.hihoulang.com'
  cname: true

# zap logger configuration
zap:
  # 可使用 "debug", "info", "warn", "error", "dpanic", "panic", "fatal",
  level: 'info'
  # console: 控制台, json: json格式输出
  format: 'console'
  prefix: '[APK-LINK]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  # LowercaseLevelEncoder:小写
  # LowercaseColorLevelEncoder:小写带颜色
  # CapitalLevelEncoder: 大写
  # CapitalColorLevelEncoder: 大写带颜色,
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# log configuration
log:
  prefix: '[APK-LINK]'
  log-file: true
  stdout: 'debug'
  file: 'debug'

jwt:
  signing-key: 'houlang-apk-link'