# system configuration
system:
  use-multipoint: false
  env: 'public'
  addr: 5050
#  db-type: 'mysql'

# mysql configuration
mysql:
  username: root
  password: 'kel317-+'
  #  password: '123456'
  path: '127.0.0.1:3306'
  db-name: 'linking_db'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  max-idle-conns: 50
  max-open-conns: 100
  log-mode: false

# redis configuration
redis:
  addr: '127.0.0.1:6379'
  password: ''
  db: 0

# log configuration
log:
  prefix: '[LINKING-API]'
  log-file: true
  stdout: 'debug'
  file: 'debug'

jwt:
  signing-key: 'houlang-linking'